name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@baba5489c6b4b4b33ea94a953307802305d673ef
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
